import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import toast from 'react-hot-toast';

import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import FormField from '../components/FormField';
import Loader from '../components/Loader';

const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const generateImage = async () => {
    if (form.prompt) {
      try {
        setGeneratingImg(true);
        const response = await fetch('http://localhost:8080/api/v1/imagix', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ prompt: form.prompt }),
        });
        const data = await response.json();

        // Use mimeType from backend, fallback to jpeg
        const mimeType = data.mimeType || 'image/jpeg';
        setForm({ ...form, photo: `data:${mimeType};base64,${data.photo}` });
        toast.success('Image generated successfully!');

      } catch (error) {
        toast.error('Failed to generate image. Please try again.');
      } finally {
        setGeneratingImg(false);
      }
    } else {
      toast.error('Please enter a prompt to generate an image.');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (form.prompt && form.photo) {
      setLoading(true);
      try {
        const response = await fetch('http://localhost:8080/api/v1/post', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(form),
        });

        await response.json();
        toast.success('Shared with the community!');
        setTimeout(() => navigate('/'), 1000);
      } catch (error) {
        toast.error('Failed to share prompt. Please try again.');
      } finally {
        setLoading(false);
      }
    } else {
      toast.error('Please enter a prompt and generate an image first.');
    }
  };

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({ ...form, prompt: randomPrompt });
  };

  return (
    <motion.section 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className='max-w-7xl mx-auto'
    >
      <div>
        <h1 className='font-extrabold text-[40px] md:text-[52px] text-gray-900 dark:text-transparent dark:bg-clip-text dark:bg-gradient-to-r dark:from-purple-400 dark:to-cyan-400 drop-shadow-[0_0_15px_rgba(168,85,247,0.3)]'>Create</h1>
        <p className='mt-4 text-gray-600 dark:text-slate-400 text-[16px] max-w-[500px] leading-relaxed'>
          Create imaginative and visually stunning images generated by <span className='text-purple-600 dark:text-cyan-400 font-semibold'>IMAGIX AI</span>
          and share them with the community
        </p>
      </div>
      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            labelName='Your Name'
            type='text'
            name='name'
            placeholder='Ex., John Doe'
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName='Prompt'
            type='text'
            name='prompt'
            placeholder='A plush toy robot sitting against a yellow wall...'
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
          <div className={`relative bg-gray-100 dark:bg-[#1a1d2d] border ${generatingImg ? 'border-purple-500 dark:border-cyan-500 shadow-[0_0_20px_rgba(168,85,247,0.4)] dark:shadow-[0_0_20px_rgba(34,211,238,0.4)] animate-pulse' : 'border-gray-300 dark:border-gray-700'} text-gray-900 text-sm rounded-lg w-64 p-3 h-64 flex justify-center items-center transition-all duration-300`}>
            {form.photo ? (
              <img
                src={form.photo}
                alt={form.prompt}
                className='w-full h-full object-contain rounded-md'
              />
            ) : (
              <img
                src={preview}
                alt='preview'
                className='w-9/12 h-9/12 object-contain opacity-40 dark:invert'
              />
            )}
            {generatingImg && (
              <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(255,255,255,0.5)] dark:bg-[rgba(0,0,0,0.5)] rounded-lg'>
                <Loader />
              </div>
            )}
          </div>
        </div>

        <div className='mt-5 flex gap-5'>
          <button
            type='button'
            onClick={generateImage}
            className='text-white font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center bg-gradient-to-r from-emerald-500 to-teal-400 hover:shadow-[0_0_15px_rgba(16,185,129,0.5)] hover:scale-105 transition-all duration-300'
          >
            {generatingImg ? 'Generating...' : 'Generate Art'}
          </button>
        </div>

        <div className='mt-10'>
          <p className='mt-2 text-gray-600 dark:text-slate-400 text-[14px] leading-relaxed'>
            Once you have created the image you want, you can share it with
            others in the community
          </p>
          <button
            type='submit'
            className='mt-3 text-white font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center bg-gradient-to-r from-purple-500 to-cyan-500 hover:shadow-[0_0_15px_rgba(168,85,247,0.5)] hover:scale-105 transition-all duration-500'
          >
            {loading ? 'Sharing...' : 'Share with the community'}
          </button>
        </div>
      </form>
    </motion.section>
  );
};

export default CreatePost;