import React, { useState, useEffect } from 'react';
import { Card, FormField, Loader } from '../components';
import { motion } from 'framer-motion';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState([]);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch('http://localhost:8080/api/v1/post', {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
        });
        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data.reverse()); // newest first
        }
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchedResults = allPosts.filter(
          (post) =>
            post.name.toLowerCase().includes(e.target.value.toLowerCase()) ||
            post.prompt.toLowerCase().includes(e.target.value.toLowerCase())
        );
        setSearchedResults(searchedResults);
      }, 500)
    );
  };

  return (
    <section className='max-w-7xl mx-auto'>
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className='flex flex-col items-center justify-center text-center mb-10'
      >
        <h1 className='font-extrabold text-[40px] md:text-[52px] bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-cyan-400 drop-shadow-[0_0_15px_rgba(168,85,247,0.3)]'>
          The Community Showcase
        </h1>
        <p className='mt-4 text-slate-400 text-[16px] max-w-[600px] leading-relaxed'>
          Browse through a collection of imaginative and visually stunning images generated by <span className='text-cyan-400 font-semibold'>IMAGIX</span>
        </p>
      </motion.div>
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6, delay: 0.3 }}
        className='mt-16'
      >
        <FormField
          labelName='Search posts'
          type='text'
          name='text'
          placeholder='Search posts by name or prompt...'
          value={searchText}
          handleChange={handleSearchChange}
        />
      </motion.div>
      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-slate-400 text-xl mb-3'>
                Showing results for{' '}
                <span className='text-white'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title='No search results found'
                />
              ) : (
                <RenderCards data={allPosts} title='No posts found' />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;