import React, { useState, useEffect } from 'react';
import { Card, FormField } from '../components';
import { motion, AnimatePresence } from 'framer-motion';
import toast from 'react-hot-toast';

const SkeletonCard = () => (
  <div className='rounded-xl relative h-64 bg-gray-200 dark:bg-[#1a1d2d] animate-pulse overflow-hidden shadow-[0_0_15px_rgba(0,0,0,0.1)] dark:shadow-[0_0_15px_rgba(0,0,0,0.5)]'>
    <div className='absolute bottom-0 left-0 right-0 m-2 p-4 h-24 bg-white/80 dark:bg-gray-800 rounded-lg backdrop-blur-sm'>
      <div className='w-3/4 h-4 bg-gray-300 dark:bg-gray-600 rounded mb-2'></div>
      <div className='flex items-center gap-2 mt-4'>
        <div className='w-7 h-7 rounded-full bg-gray-300 dark:bg-gray-600'></div>
        <div className='w-1/3 h-4 bg-gray-300 dark:bg-gray-600 rounded'></div>
      </div>
    </div>
  </div>
);

const RenderCards = ({ data, title, onImageClick }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} onClick={() => onImageClick(post)} />);
  }
  return (
    <h2 className='mt-5 font-bold text-cyan-400 text-xl uppercase'>{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState([]);
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [selectedImage, setSelectedImage] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const response = await fetch('http://localhost:8080/api/v1/post', {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
        });
        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data.reverse());
        }
      } catch (error) {
        toast.error('Failed to load images');
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchedResults = allPosts.filter(
          (post) =>
            post.name.toLowerCase().includes(e.target.value.toLowerCase()) ||
            post.prompt.toLowerCase().includes(e.target.value.toLowerCase())
        );
        setSearchedResults(searchedResults);
      }, 500)
    );
  };

  return (
    <section className='max-w-7xl mx-auto'>
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className='flex flex-col items-center justify-center text-center mb-10'
      >
        <h1 className='font-extrabold text-[40px] md:text-[52px] text-gray-900 dark:text-transparent dark:bg-clip-text dark:bg-gradient-to-r dark:from-purple-400 dark:to-cyan-400 drop-shadow-[0_0_15px_rgba(168,85,247,0.3)]'>
          The Community Showcase
        </h1>
        <p className='mt-4 text-gray-600 dark:text-slate-400 text-[16px] max-w-[600px] leading-relaxed'>
          Browse through a collection of imaginative and visually stunning images generated by <span className='text-purple-600 dark:text-cyan-400 font-semibold'>IMAGIX</span>
        </p>
      </motion.div>
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6, delay: 0.3 }}
        className='mt-16'
      >
        <FormField
          labelName='Search posts'
          type='text'
          name='text'
          placeholder='Search posts by name or prompt...'
          value={searchText}
          handleChange={handleSearchChange}
        />
      </motion.div>
      <div className='mt-10'>
        {loading ? (
          <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
            {Array.from({ length: 8 }).map((_, i) => <SkeletonCard key={i} />)}
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-gray-500 dark:text-slate-400 text-xl mb-3'>
                Showing results for{' '}
                <span className='text-gray-900 dark:text-white'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title='No search results found'
                  onImageClick={setSelectedImage}
                />
              ) : (
                <RenderCards data={allPosts} title='No posts found' onImageClick={setSelectedImage} />
              )}
            </div>
          </>
        )}
      </div>

      <AnimatePresence>
        {selectedImage && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center bg-gray-900/40 dark:bg-black/80 backdrop-blur-sm p-4"
            onClick={() => setSelectedImage(null)}
          >
            <div className="relative max-w-5xl w-full max-h-[90vh] flex justify-center object-contain" onClick={e => e.stopPropagation()}>
               <motion.img 
                 initial={{ scale: 0.9 }}
                 animate={{ scale: 1 }}
                 exit={{ scale: 0.9 }}
                 src={selectedImage.photo}
                 alt={selectedImage.prompt} 
                 className="max-h-[90vh] w-auto rounded-lg shadow-[0_0_40px_rgba(0,0,0,0.2)] dark:shadow-2xl object-contain border border-gray-200 dark:border-gray-700 bg-white dark:bg-transparent"
               />
               <button onClick={() => setSelectedImage(null)} className="absolute -top-4 -right-4 text-gray-800 dark:text-white bg-white dark:bg-black hover:bg-gray-100 dark:hover:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-full w-10 h-10 flex items-center justify-center transition-all shadow-lg text-xl z-50">✕</button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  );
};

export default Home;